### ISSUE TITLE
Error: failed to load wallet: Wrong sequence_idx - Intermittent Issue

### ISSUE THREAD

**Issue by johnalanwoods** [LedgerHQ/ledger-app-monero#42] opened 2019-06-21 16:14 UTC
When using my Nano X with the Monero Core CLI Wallet

CLI Wallet: v0_14_1_0
Nano X FW: v1_2_4-1
Monero Client App on X: v1_3_1

I **intermittently** get this message 

    Error: failed to load wallet: Wrong sequence_idx

It occurs about 50%-70% of the time.

I generated the wallet files using this command.

    --generate-from-device <new-wallet-name> --subaddress-lookahead 3:200 

When it works I can see my balance and all looks correct.

Is this a Nano X issue?

**Comment by johnalanwoods** [comment] 2019-06-21 16:43
Happens with my NanoS too on v1_3_1

**Comment by johnalanwoods** [comment] 2019-06-21 17:42
Reoccurrence of https://github.com/monero-project/monero/pull/4643?

**Comment by selsta** [comment] 2019-06-22 02:42
Did you make sure that Ledger Live is closed while trying? It can interfere.

**Comment by johnalanwoods** [comment] 2019-06-22 06:43
It was closed but previously open in the same boot session. I will reboot and retest.

**Comment by johnalanwoods** [comment] 2019-06-22 08:23
Nah issue persists even after a clean boot. It's intermittent though, i.e. 50-70% of the time.

**Comment by johnalanwoods** [comment] 2019-06-22 08:24
@cslashm Are you seeing this at all in your testing? By the way I'm on macOS Mojave.

**Comment by tficharmers** [comment] 2019-06-22 15:31
I can also confirm I have experienced this twice on macOS Mojave. Ledger Live was closed.

**Comment by selsta** [comment] 2019-06-22 15:32
@tficharmers Also with v0.14.1.0 ?

**Comment by tficharmers** [comment] 2019-06-22 15:37
@selsta yes. 0.14.1.0 CLI on Nano S. MacOS 10.14.5 (18F132).

1) The first time I entered the password once and had this error. Tried again without unplugging and it happened again. Unplugged, replugged and it worked.

2) The second time, I entered the password and saw the error. I tried again without unplugging and it worked.

I will do more testing.

**Comment by johnalanwoods** [comment] 2019-06-23 06:01
I wonder if this might delay the public launch. It’s been solved before so probably straightforward.

**Comment by selsta** [comment] 2019-06-25 09:53
I can reproduce this now, it only happens with the reproducible build version of v0.14.1.0, if I compile myself it’s working fine. I guess it has something to do with the hidapi version used for reproducible builds?

**Comment by cslashm** [comment] 2019-06-25 10:40
Thank you @selsta for investigating the bug.

But I don't understand why only deterministic build trigger the pb? It use the same hid-api version as for non deterministic build, no?

And the 0.8-rc1 was already the one used in 0.14.0.2

**Comment by selsta** [comment] 2019-06-25 10:42
@cslashm We installed master on the macOS build server.

**Comment by cslashm** [comment] 2019-06-25 10:44
ouch. I guess it will be fixed on next build

is a 0.14.1.1  on the road?

**Comment by selsta** [comment] 2019-06-25 10:45
@cslashm Yes, I think so. Luckily this bug isn’t too bad because you just have to try again a few times for it to work.

**Comment by cslashm** [comment] 2019-06-25 10:46
Ok, nice.

I also inform our support about this issue and workaround.

**Comment by johnalanwoods** [comment] 2019-06-25 12:11
@selsta @cslashm - so in the mean time between now and 0.14.1.1, you think it's safe to use Ledger with Monero core, just by retrying until you 'get in'?

@selsta should I create a bug on the Monero codebase?

**Comment by johnalanwoods** [comment] 2019-06-27 10:33
I complied myself and still have the issue.

hidapi: stable 0.8.0-rc1 (bottled), HEAD
Library for communicating with USB and Bluetooth HID devices
https://github.com/signal11/hidapi
/usr/local/Cellar/hidapi/0.8.0-rc1 (17 files, 131.1KB) *
  Poured from bottle on 2019-06-25 at 14:02:38

**Comment by johnalanwoods** [comment] 2019-06-27 13:20
Ok, can confirm using head on hidapi works. This just needs an update on the Monero end.

**Comment by TheCharlatan** [comment] 2019-06-27 15:37
The next release of monero will be built with version 0.9.0 of https://github.com/libusb/hidapi , pull request to change this in the reproducible build system is open: https://github.com/monero-project/monero/pull/5703

**Closed** 2020-03-31 09:21 UTC
