### ISSUE TITLE
Full Monero public address not displaying on Ledger.

### ISSUE THREAD

**Issue by aeonminingpool-com** [LedgerHQ/ledger-app-monero#18] opened 2018-06-05 17:33 UTC
First of all thank you for all of your efforts. I am glad XMR can be protected on a hardware device now.

I have two Monero wallets on the ledger. One with pass phrase and one without.

The Monero wallet attached to pin with 24 seed, no pass phrase does not display the ENTIRE public address on the ledger.

It displays and scrolls about 60 percent of it and then scrolls back.

The second wallet with pass phrase however displays the entire public address.

Bug seems entirely cosmetic as everything appears functional when interacting with blockchain.

The address displayed is correct it just doesn’t display ALL of it.

I hope this can help please let me know if I can clarify any details.

**Comment by cslashm** [comment] 2018-06-05 18:27
Confirmed.

It will be fixed shortly after the release 1.0.0 of the app

**Comment by Mansarde** [comment] 2018-07-12 17:23
I have the same issue (on v1.0.0 of the app), but for me it doesn't even scroll past the first 11 characters.
(The 11th character shows a pixel stretch effect before it returns scrolling back again).
And it's also not on the wallet attached to the 24 seed, but attached to a 24 + passphrase seed.

I tried other 24 + passphrase seeds and it scrolls all the way for them, as well as for the 24 seed only.
It just happens to not scroll all the way on the 24 + passphrase seed that I actually *use*.
Just my luck.^^

**Comment by sammy007** [comment] 2018-10-21 18:55
> It will be fixed shortly

Skeleton waiting.

**Comment by silvermar** [comment] 2018-11-01 19:39
I know time is relative but I'd really like to be able to see my entire address on the ledger display. A status update would be nice...thanks a bunch for the work on the ledger app!

**Comment by cslashm** [comment] 2019-01-23 13:34
seems fixed

**Closed by cslashm** 2019-01-23 13:34 UTC
Labels: bug

**Comment by Mansarde** [comment] 2019-01-23 17:40
> seems fixed

Is it fixed in the app in Ledger Live? I just ask because Ledger Live only shows the v1.1.1 app whereas the release page on here shows v1.1.2 as the latest version.

**Comment by Mansarde** [comment] 2019-02-11 14:12
Hey @cslashm 
My Ledger Nano S is updated to firmware v1.5.5 and Monero app v1.1.2
Unfortunately I still have the problem (like the OP originally mentioned) that my public address is not scrolling through completely. It appears to stop scrolling after some characters.

This only happens with a specific passphrase.
If I only use the seed or use another passphrase then the address scrolls through without any problems.
I guess it only seems to affect certain addresses or seed+passphrase combinations?

I'm happy to provide you with any logs or settings, just tell me what you need and I'll oblige. :)

**Comment by Mansarde** [comment] 2019-02-19 16:03
Just wanted to report that with the Monero app v1.1.3 I (obviously) don't have the scrolling problem anymore. :)

**Comment by cslashm** [comment] 2019-02-19 16:06
@Mansarde  1.1.2 and 1.1.3 are only available on 1.5.5 firmware

no more scroll! Press both button on your pub address to show the full address.

**Comment by Mansarde** [comment] 2019-02-19 16:09
Oh, I saw the abbreviated address, but didn't know about the double-press for showing the whole address.
Just tried it and it works without problems, yay!
Many thanks! :D
